title: "Paul LIN"
author: "Paul Lin"
description: "Welcome to My Personal Page"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false             # show article excerpts instead of archive list on the home page
show_frame: true                # display a grey frame on large screens
show_sidebar: false             # show a sidebar instead of the usual header
show_minimal: false             # remove all clutter

show_frame: "/assets/images/unicornbg.svg"

# Menu                          # for available icons see https://fontawesome.com/v5/icons/

navigation:                     # accepts {file, title, url, icon, sidebaricon}
  - {title: "Agentic/LLM Engineering", file: "ai.html"}
  - {title: "ML/Data Science", file: "ds.html"}
  - {title: "Strategy/Transformation", file: "bg.html"}

external:                       # accepts {file, title, url, icon, sidebaricon}
  - {title: Mail, icon: envelope, url: "mailto:lsanchuan.m21@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/linscpaul"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""         # see https://disqus.com
#  isso_domain: ""              # see https://isso-comments.de

plugins:
 - jekyll-feed

collections:
  aiposts:
    output: true
    permalink: /ai/:name/

  dsposts:
    output: true
    permalink: /ds/:name/

  bgposts:
    output: true
    permalink: /bg/:name/
